### PR TITLE
added markdown

### PR DESCRIPTION
**Pull request by GreenMain**
Python markdown sucks for some reason så bruger javascripts istedet

### CODE REVIEW

**Review by mikejensen0 — APPROVED** [review]
lgtm

**Comment by GreenMain** [comment]
Go to line 35-41 in the client.js file and judge what you think about the variable names and if it is fairly clear what is going on. Furthermore i also noticed that on certain prompts our API could give an exception but simply repeating the prompt often solved this so added some logic so the code simply repeats the prompt if an exception is given. I realize this second part polutes the PR a bit but i deemed it acceptable as it is an extremely small change. It imports a python library, adds it to our requirement txt file and adds a single line to one of our methods.

**Comment by GreenMain** [comment]
Can also add that if the first thing the ai writes is some code there will be a small amount of whitespace. But i think this is acceptable

**Review by mikejensen0 — APPROVED** [review]
lgtm, but i tried to fix the trimming with regex to make it more tidy. please confirm if it does the same as intended

**Pull request merged**
